server:
  port: 8002
eureka:
  instance:
    prefer-ip-address: true # 显示主机的IP
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/   # 指定服务端地址
spring:
  application:
    name: ms-user1










